#!/bin/bash
#
# Perform necessary crystal setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

ln -nfs /opt/crystal/bin/crystal /usr/bin/crystal

exit 0
